<a href="https://colab.research.google.com/github/HarinCoder/HarinCoder/blob/main/Harin_Day08_DIY_Solution_Doc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Define a NumPy array with 4*5 dimensions, and swap the array's dimensions to make it 5*4 using suitable functions.

In [ ]:
import numpy as np

a = np.arange(20)
print("original array", a)

c = np.arange(20).reshape(4,5)
print("reshape array", c)

b = c.T
print("transpose array:", b)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
reshape array [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
transpose array: [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


Write   a   Python   program   to   create   two   2-dimensional   arrays   and   applyhstack(), vstack(), concatenate(), and split()functions to them to get the output as shown below

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
print("first array")
print(a)

b = np. array([[6,7],[8,9]])
print("second array")
print(b)

c = np.hstack((a,b))
print("applying hstacking")
print(c)

d = np.vstack((a,b))
print("applting vstacking")
print(d)

e = np.concatenate((a,b), axis = None)
print("applying concatenate function() ")
print(e)

f = np.split(e,2)
print("applying split function()")
print(f)

first array
[[1 2]
 [3 4]]
second array
[[6 7]
 [8 9]]
applying hstacking
[[1 2 6 7]
 [3 4 8 9]]
applting vstacking
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
applying concatenate function() 
[1 2 3 4 6 7 8 9]
applying split function()
[array([1, 2, 3, 4]), array([6, 7, 8, 9])]
