<a href="https://colab.research.google.com/github/HarinCoder/HarinCoder/blob/main/Important_Numpy_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 1. import numpy as np and see the version


In [ ]:
import numpy as np

print(np.__version__)


1.22.4


2. create a 1d array of numbers from 0 to 9


In [ ]:
import numpy as np

i = np.array([1,2,3,4,5,6,7,8,9])
print(i)

[1 2 3 4 5 6 7 8 9]


3. create a 3x3 numpy array of all true's


In [ ]:
import numpy as np

i = np.array([1,2,3,4,5,6,7,8,9])
k = i.reshape(3,3)
print(k)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


4.extract all odd numbers from arr 


In [ ]:
import numpy as np

i = np.array([1,2,3,4,5,6,7,8,9])
j = (i % 2 == 1)
odd_nmbrs = i[j]
print(odd_nmbrs)


[1 3 5 7 9]


5. replace all odd numbers in arr with -1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1
print(arr)


[-1  2 -1  4 -1  6 -1  8 -1]


6. replace all odd numbers in arr with -1 without changing arr


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

new_arr = np.where(arr % 2 == 1, -1, arr)
print("Original Array:", arr)
print("New Array:", new_arr)


Original Array: [1 2 3 4 5 6 7 8 9]
New Array: [-1  2 -1  4 -1  6 -1  8 -1]


7. convert a 1d array to a 2d array with 2 rows


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

ar2 = arr.reshape(4,2)
print(ar2)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


8. how to stack arrays a and b vertically


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack((a, b))
print(c)



[[1 2 3]
 [4 5 6]]


9. how to stack arrays a and b horizontally


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack((a, b))
print(c)



[1 2 3 4 5 6]


10. create the following pattern without hardcoding use only numpy function and below input array a
array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])

In [ ]:
import numpy as np

a = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
pattern = np.concatenate((np.repeat(a, 3), np.tile(np.array([1, 2, 3]), 3)))

print(pattern)


[1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 1 2 3 1 2 3 1 2 3]
