<a href="https://colab.research.google.com/github/HarinCoder/HarinCoder/blob/main/numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Concatenate array : multiple arrays are merged to form new array that contain all array


In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([5,6])

c = np.concatenate((a,b), axis = None)

print(c)

[1 2 3 4 5 6]


stack and colum stack

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([5,6,7])

c = np.stack((a,b))
#---
d = np.array([1,2,3])
e = np.array([5,6,7])

f = np.column_stack((d,e))
print(f)

#size of the arrays must be equal

[[1 5]
 [2 6]
 [3 7]]


hstack: add second array to column of first array and vstack: 

In [ ]:
a = np.array([1,2,3])
b = np.array([5,6,7])

i = np.hstack((a,b))           .vstack(())
print(i)

[1 2 3 5 6 7]


splitting arrays - split(), hsplit(), vsplit()

In [ ]:
import numpy as np

x = np.arange(12)
y = np.split(x,3)
print(y)

#split into multiple sub array

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [ ]:
import numpy as np

a = np.arange(16).reshape(4,4)
print(a)
[b,c] = np.hsplit(a,2)
print("b: ", b)
print("c: ",c)

#[b,c] = np

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b:  [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
c:  [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
import numpy as np

a = np.arange(16).reshape(4,4)
print(a)
[b,c] = np.vsplit(a,2)
print("b: ", b)
print("c: ",c)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b:  [[0 1 2 3]
 [4 5 6 7]]
c:  [[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:

j = np.arange(10)
i = np.split(x,)

print(np.split(i,2))

Raval array

In [ ]:
import numpy as numpy

a = np.arange(20).reshape(4,5)
print(a)
b = a.T
print(b)
c = b.ravel()
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[ 0  5 10 15  1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19]


Pandas creating data frame

In [ ]:
import numpy as np
import pandas as pd

#creating dataframe from list

i = ['a','b','c','d','e']
j = pd.DataFrame(i)
print(j)


#craeting dataframe from dict

a = [{"a": 1, "b":2, "c":3}]
b = pd.DataFrame(a, index = ["first","second","third"])
print(b)

   0
0  a
1  b
2  c
3  d
4  e
        a  b  c
first   1  2  3
second  1  2  3
third   1  2  3


Representing feathures of data

In [ ]:
import pandas as pd

i = pd.Series([19,24,36], index= ["small","medium","large"])
print(i)

j = i.index
k = i.values
print(k)

small     19
medium    24
large     36
dtype: int64
[19 24 36]


In [ ]:
import pandas as pd

x = [1,2,3]
i = pd.Series(x)
j  = pd.Series(x, index= ['a','b','c'])
k = ("the third element is ", x[2])
l = ("the first two elements are ", x[1:])
m = ("the element having index B is ",j["b"])

print(i)
print(j)
print(k)
print(l)
print(m)





0    1
1    2
2    3
dtype: int64
a    1
b    2
c    3
dtype: int64
('the third element is ', 3)
('the first two elements are ', [2, 3])
('the element having index B is ', 2)


In [ ]:
import pandas as pd

s = pd.Series(['amit','bob','kate','a','b','car','dog','cat'])
print(s.str.lower())
print(s.str.upper())
print(s.str.len())


0    amit
1     bob
2    kate
3       a
4       b
5     car
6     dog
7     cat
dtype: object
0    AMIT
1     BOB
2    KATE
3       A
4       B
5     CAR
6     DOG
7     CAT
dtype: object
0    4
1    3
2    4
3    1
4    1
5    3
6    3
7    3
dtype: int64


Combain data using pandas

In [ ]:
import pandas as pd
import numpy as np

np.random.seed()
i = np.random.randint(1,100,(4,3))
print(i)
df = pd.DataFrame(i, columns = list("abc"), index = list("wxyz"))
print(df)




[[17 92 74]
 [28 89 38]
 [28 16  4]
 [72 63 91]]
    a   b   c
w  17  92  74
x  28  89  38
y  28  16   4
z  72  63  91
