<a href="https://colab.research.google.com/github/HarinCoder/HarinCoder/blob/main/numpy_quest_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 get the common items between c and d array


In [ ]:
import numpy as np

c = np.array([1, 2, 3, 4, 5])
d = np.array([4, 5, 6, 7, 8])

common_items = np.intersect1d(c, d)
print(common_items)


[4 5]


from array c remove all items present in array d


In [ ]:
import numpy as np

c = np.array([1, 2, 3, 4, 5])
d = np.array([3, 4, 5, 6, 7])

c = np.setdiff1d(c, d)

print(c)  # Output: [1 2]


[1 2]


get the postions where elements of c and d match

In [ ]:
import numpy as np

c = np.array([1, 2, 3, 4, 5])
d = np.array([3, 2, 3, 0, 6])

match_positions = np.where(c == d)[0]
print(match_positions)


[1 2]


get all items between 5 and 10 from array 

In [ ]:
import numpy as np

# create the array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

result = arr[(arr >= 5) & (arr <= 10)]

# print the result
print(result)


[ 5  6  7  8  9 10]


how to make a python function that handles scalare to work on numpy arrays and convert function maxx that works on two scalars to work on two arrays

In [ ]:
import numpy as np

def maxx(x, y):
    if x > y:
        return x
    else:
        return y

# New function that works on arrays using NumPy's maximum function
def maxx_arr(x_arr, y_arr):
    return np.maximum(x_arr, y_arr)

# Example usage with NumPy arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 2, 1, 5])
result = maxx_arr(arr1, arr2)
print(result)


[3 2 3 5]


 swap columns 1 and 2 in the array


In [3]:
import numpy as np

# Create a 2D array with 3 rows and 4 columns
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Swap columns 1 and 2
arr[:,[1,0]] = arr[:,[0,1]]
# Print the resulting array
print(arr)


[[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]]


 swap rows 1 and 2 in the array


In [7]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13,14,15,16]])

arr[[0,2,1,3], :]
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


 reverse the rows of 2d array


In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13,14,15,16]])
array_reverse = np.flip(arr, axis=0)
print(array_reverse)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


 reverse the columns of a 2d array


In [17]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)

reversed_arr = arr[:, ::-1]
print("Reversed columns:\n", reversed_arr)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


 create a 2d array of shape 5x3 to contain random decimal numbers between 5 and 10


In [18]:
import numpy as np

arr = np.random.uniform(low= 5.0, high=10.0,size =(5,4))
print(arr)
 

[[9.80356268 7.32963692 9.35956841 5.58651037]
 [6.43109237 6.77321915 5.14818901 7.21863419]
 [5.42303762 9.2660685  7.23914423 9.03980889]
 [8.04851635 9.08194483 8.76246563 5.75751817]
 [6.92005858 7.84131826 5.15619921 7.96622647]]
